"""Menu of services table

Revision ID: 6b0b5f7497e0
Revises: dc5279fbcb68
Create Date: 2023-06-08 15:28:19.896673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0b5f7497e0'
down_revision = 'dc5279fbcb68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
