"""Menu of services table created

Revision ID: b07057944621
Revises: 6b0b5f7497e0
Create Date: 2023-06-08 15:31:12.362015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07057944621'
down_revision = '6b0b5f7497e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
