"""update dog

Revision ID: c61ac864c9cb
Revises: df0f0e5b1378
Create Date: 2023-06-06 13:14:07.998879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61ac864c9cb'
down_revision = 'df0f0e5b1378'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'dogs', type_='foreignkey')
    op.create_foreign_key(None, 'dogs', 'owners', ['owner_id'], ['id'])
    op.drop_column('dogs', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('owner', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'dogs', type_='foreignkey')
    op.create_foreign_key(None, 'dogs', 'owners', ['owner'], ['name'])
    op.drop_column('dogs', 'owner_id')
    # ### end Alembic commands ###
