"""bind=engine

Revision ID: dc5279fbcb68
Revises: ce1e57f841d2
Create Date: 2023-06-07 17:44:19.653324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5279fbcb68'
down_revision = 'ce1e57f841d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
