"""update dog

Revision ID: df0f0e5b1378
Revises: 3f278f752539
Create Date: 2023-06-06 13:01:27.500696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0f0e5b1378'
down_revision = '3f278f752539'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
